name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Mengeksekusi perintah di Server cPanel
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }} # <--- INI BARIS TAMBAHANNYA
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/USERNAME_CPANEL_ANDA/cleohotels
          
          git pull origin main
          
          npm install
          npm run build
          
          mkdir -p tmp
          touch tmp/restart.txt

           