name: Deploy to cPanel

on:
  push:
    branches:
      - main # Pastikan sesuai dengan nama branch utama Anda (main/master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Mengeksekusi perintah di Server cPanel
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }} # <--- Menggunakan Password cPanel
        port: ${{ secrets.SSH_PORT }}
        script: |
          # 1. Masuk ke folder project Anda (Ubah path di bawah ini!)
          cd /home/balibite/cleohotels.id
          
          # 2. Tarik kode terbaru
          git pull origin main
          
          # 3. Install dan Build Next.js
          npm install
          npm run build
          
          # 4. Trik Auto-Restart Node.js App
          mkdir -p tmp
          touch tmp/restart.txt
          